# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Dependencies
        run: npm install

      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Make gradlew executable
        run: chmod +x ./Code/gradlew

      - name: Build the app
        run: ./Code/gradlew build
        
  test:
    # The type of runner that the job will run on
    name: unit tests
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Dependencies
        run: npm install

      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Make test executable
        run: | 
            chmod +x ./Code/app/src/test/java/com/example/mobilibrary/BookTest.java 
            chmod +x ./Code/app/src/test/java/com/example/mobilibrary/UserTest.java 
            chmod +x ./Code/app/src/test/java/com/example/mobilibrary/bookStatusTest.java
          
      - name: Unit tests
        run: | 
            ./Code/app/src/test/java/com/example/mobilibrary/BookTest.java 
            ./Code/app/src/test/java/com/example/mobilibrary/UserTest.java 
            ./Code/app/src/test/java/com/example/mobilibrary/bookStatusTest.java
