# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Dependencies
        run: npm install

      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Make gradlew executable
        run: chmod +x ./Code/gradlew

      - name: Build the app
        run: ./gradlew build
        working-directory: Code
        
  #Run instrumental tests     
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      #used to allow gradlew to be executable (permission issues)
      - name: Make gradlew executable
        run: chmod +x ./Code/gradlew
        
      # sets up the android environment (UI) and which files to run
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew
          working-directory: Code
          
  Unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Make gradlew executable
        run: chmod +x ./Code/gradlew
        
        # Working directory states which directory to start in (used since multiple files)
      - name: Run unit tests
        run: ./gradlew test
        working-directory: Code
